from pathlib import Path

ROOT_DIR = Path(__file__).parent
ASSETS_DIR = ROOT_DIR / 'assets'
IMG_DIR = ASSETS_DIR / 'img'
WINDOW_ICON_PATH = IMG_DIR / 'icon.png'

BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500
